// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyWJkfzWEZh30uwvWJK6h32cjk1yqQasw',
    appId: '1:550090711196:web:f9fb84fed012a95b6e8d59',
    messagingSenderId: '550090711196',
    projectId: 'payroll-borna',
    authDomain: 'payroll-borna.firebaseapp.com',
    storageBucket: 'payroll-borna.appspot.com',
    measurementId: 'G-6NLS4DWXRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvFQoS0X1JGT2D7x32YwQjxlAEfuJLShE',
    appId: '1:550090711196:android:05892108a3005b366e8d59',
    messagingSenderId: '550090711196',
    projectId: 'payroll-borna',
    storageBucket: 'payroll-borna.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUg2IbZcQJOonXfIe4NSPozGYJmiwaTl4',
    appId: '1:550090711196:ios:1d581f658922631b6e8d59',
    messagingSenderId: '550090711196',
    projectId: 'payroll-borna',
    storageBucket: 'payroll-borna.appspot.com',
    iosClientId:
        '550090711196-jov57pv0p1g2j6dc59va87ikpqo3o9m5.apps.googleusercontent.com',
    iosBundleId: 'ca.optimasoft.app',
  );
}
