# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  # before_all do
  #   ENV["FASTLANE_DONT_STORE_PASSWORD"] = "1"
  #   ENV["FASTLANE_PASSWORD"] = ""
  # end
  desc "Description of what the lane does"
  lane :beta do
    build_ios_app(export_method: 'app-store')
    upload_to_testflight
  end
end
